### ISSUE TITLE
Checks, checks and maybe..... some checks?))))))

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#10]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/e0a7a51d042aeea3714ce6badce73c1b37548d97/HomeTask9_%E2%84%964/HomeTask9_%E2%84%964.py#L29-L30

**Comment by IgnatGrischuk** [comment]
Fixed.
