### ISSUE TITLE
Please rename the variables. What are the value one two three for the sphere? We have concrete names: x y z or smth like that

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#11]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/e0a7a51d042aeea3714ce6badce73c1b37548d97/HomeTask9_%E2%84%964/HomeTask9_%E2%84%964.py#L6

**Comment by IgnatGrischuk** [comment]
The variable names have been changed, and comments in the code have also been corrected.
