### ISSUE TITLE
The solution is redundant, we need to check absolutely any string for palindromy, not just the human-sense one

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#12]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/e0a7a51d042aeea3714ce6badce73c1b37548d97/HomeTask9_%E2%84%965/HomeTask9_%E2%84%965.py#L9

**Comment by IgnatGrischuk** [comment]
Fixed.
