### ISSUE TITLE
Please remove obvious comments and replace the rest to their english analogues

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#13]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/e0a7a51d042aeea3714ce6badce73c1b37548d97/HomeTask9_%E2%84%965/HomeTask9_%E2%84%965.py#L14-L20

**Comment by IgnatGrischuk** [comment]
Fix comments and replace them. Check it)
