### ISSUE TITLE
Incorrect code style. Single line comments must be placed above the line of code you are explaining or just to the right in the same line, not below the line

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#14]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/e0a7a51d042aeea3714ce6badce73c1b37548d97/HomeTask9_%E2%84%965/HomeTask9_%E2%84%965.py#L14-L15

**Comment by IgnatGrischuk** [comment]
Fix commets and replace them. Check it)
