### ISSUE TITLE
May be simplified by the use of default parameter radius=1, without setting None 

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#15]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/6e85f56ef7cae3ca73d2e09995001f3dd0807b0f/HomeTask9_%E2%84%964/HomeTask9_%E2%84%964.py#L6-L9

**Comment by IgnatGrischuk** [comment]
Fixed.
