### ISSUE TITLE
It's getting better, but it's still not enough. Imagine a user tries to set the radius as 'aboba'. Then your code will crash with an error. 

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#17]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/6e85f56ef7cae3ca73d2e09995001f3dd0807b0f/HomeTask9_%E2%84%964/HomeTask9_%E2%84%964.py#L36-L42

**Comment by IgnatGrischuk** [comment]
Fixed.
