### ISSUE TITLE
again if user sets radius as 'aboba' you get TypeError and crush with big red traceback))

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#19]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/6e85f56ef7cae3ca73d2e09995001f3dd0807b0f/HomeTask9_%E2%84%964/HomeTask9_%E2%84%964.py#L6-L22

**Comment by IgnatGrischuk** [comment]
Fixed.
