### ISSUE TITLE
Violation of the principle of single responsibility

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#2]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/e0a7a51d042aeea3714ce6badce73c1b37548d97/HomeTask9_%E2%84%962/HomeTask9_%E2%84%962.py#L3-L20

In general, the solution is workable, but it would be better to use the object's methods more wisely. If a method is responsible for adding two numbers, it should only add two numbers and return the result. Of course, all unusual situations about this specific responsibility must be handled in this method too. But it is not the object's method responsibility to output the result of adding numbers to the console. This should be done by external code.

**Comment by IgnatGrischuk** [comment]
Hope i fixed it)

**Comment by SkrytnayaRediska** [comment]
Good job! The code is nice now ;)
