### ISSUE TITLE
OK, the color has a check now, so do the same for the type

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#20]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/6e85f56ef7cae3ca73d2e09995001f3dd0807b0f/HomeTask9_%E2%84%963/HomeTask9_%E2%84%963.py#L24-L25

**Comment by IgnatGrischuk** [comment]
Fixed.
