### ISSUE TITLE
Don't give the same name to a class and an object. Use different ones

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#28]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/6e85f56ef7cae3ca73d2e09995001f3dd0807b0f/HomeTask10_%E2%84%962/HomeTask10_%E2%84%962.py#L24

**Comment by IgnatGrischuk** [comment]
I`ve chenged name for class and object.
