### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#29]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/6e85f56ef7cae3ca73d2e09995001f3dd0807b0f/HomeTask10_%E2%84%963/HomeTask10_%E2%84%963.py#L21-L35
![Снимок экрана 2024-01-25 в 17 07 29](https://github.com/IgnatGrischuk/GitExamplePY95/assets/44698380/a7e298ba-aa24-4927-9145-c8b793911661)

why both decrease and increase methods just make the speed bigger? Also why we need to pass a negative value for the decreasing method?

**Comment by IgnatGrischuk** [comment]
I`ve found solution and fix it.
