### ISSUE TITLE
Incorrect behavior

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#30]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/6e85f56ef7cae3ca73d2e09995001f3dd0807b0f/HomeTask11_%E2%84%961/HomeTask11_%E2%84%961.py#L1-L25
![Снимок экрана 2024-01-25 в 17 10 38](https://github.com/IgnatGrischuk/GitExamplePY95/assets/44698380/cde4a7d7-0393-4433-81db-2e752e02d2bb)

why only 7 numbers if i said i wanted 10

**Comment by IgnatGrischuk** [comment]
I found my mistakes, changed part of the code and added a few new lines.
