### ISSUE TITLE
May be better to use make_piza method another way

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#31]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/6e85f56ef7cae3ca73d2e09995001f3dd0807b0f/HomeTask11_%E2%84%963/HomeTask11_%E2%84%963.py#L50-L51
![Снимок экрана 2024-01-25 в 17 19 08](https://github.com/IgnatGrischuk/GitExamplePY95/assets/44698380/d225f2cc-6073-4de7-a00c-b23927ff8a51)

look at refactoring guru

**Comment by IgnatGrischuk** [comment]
I`ve think i understand, and do better than it was before.
