### ISSUE TITLE
And we need pass False every time? Looks not good

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#32]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/6e85f56ef7cae3ca73d2e09995001f3dd0807b0f/HomeTask11_%E2%84%963/HomeTask11_%E2%84%963.py#L18-L20

Better set default values for pizza parameters or use constructor without parameters and just sett False everywhere inside the constructor method

f.e.:
def __init__(self):
    self.param = False
    self.other_param = False
    etc.

**Comment by IgnatGrischuk** [comment]
I`ve set parammetrs to False, hope you`ll be satisfied) P.S: without sarcasm.
