### ISSUE TITLE
In general ok but needs for small checks

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#33]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/6e85f56ef7cae3ca73d2e09995001f3dd0807b0f/HomeTask11_%E2%84%965/HomeTask11_%E2%84%965.py#L45-L47
![Снимок экрана 2024-01-25 в 17 23 13](https://github.com/IgnatGrischuk/GitExamplePY95/assets/44698380/b09f6dde-15bd-4d85-882e-9cbf346317cb)

if the user pass strings in this calculator, you will get string concatenation. Not expected result cause our class was created as a calculator for numbers. The same for other strategies

**Comment by IgnatGrischuk** [comment]
I`ve add checks, now programm will ask the user to enter numbers.
