### ISSUE TITLE
A bit strange way to use insert queries

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#34]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/4d91223fbf7937762a8663800694ffb32014f7b2/PostgreSQL/home_task_postgresql_%E2%84%962.txt#L32-L34

insert into authors (id, first_name, last_name)
select 1, 'Александр', 'Пушкин'
where not exists  (select 1 from authors where id = 1);

but you can use insert into authors(id, first_name, last_name) values (1, 'Alex', 'P') and it will be shorter and simplier

**Comment by IgnatGrischuk** [comment]
Agree with you, fixed values where i use "select".
