### ISSUE TITLE
Please check if it is a valid year or not, user can be stupid and set anything he/she wants

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#5]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/e0a7a51d042aeea3714ce6badce73c1b37548d97/HomeTask9_%E2%84%963/HomeTask9_%E2%84%963.py#L26-L27

**Comment by IgnatGrischuk** [comment]
I`ve made a check for the entered year of manufacture.
