### ISSUE TITLE
Need add checks if the data is valid. User can set anything: empty strings, digits in the color field, special symbols etc. 

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#6]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/e0a7a51d042aeea3714ce6badce73c1b37548d97/HomeTask9_%E2%84%963/HomeTask9_%E2%84%963.py#L23-L30

**Comment by IgnatGrischuk** [comment]
Fixed.
