### ISSUE TITLE
Incorrect calculation

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#7]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/e0a7a51d042aeea3714ce6badce73c1b37548d97/HomeTask9_%E2%84%964/HomeTask9_%E2%84%964.py#L17-L18

(4 pi r^2) as i remember, not double r

**Comment by IgnatGrischuk** [comment]
Fixed.
