### ISSUE TITLE
Again need to add checks. What if the user wants to set radius as "aboba"? Your code allows to do that. 

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#8]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/e0a7a51d042aeea3714ce6badce73c1b37548d97/HomeTask9_%E2%84%964/HomeTask9_%E2%84%964.py#L6-L12

**Comment by IgnatGrischuk** [comment]
I've implemented a check to ensure that the user inputs only digits.
