### ISSUE TITLE
Check please if the radius correct or not

### ISSUE THREAD

**Issue by SkrytnayaRediska** [IgnatGrischuk/GitExamplePY95#9]
https://github.com/IgnatGrischuk/GitExamplePY95/blob/e0a7a51d042aeea3714ce6badce73c1b37548d97/HomeTask9_%E2%84%964/HomeTask9_%E2%84%964.py#L26-L27

**Comment by IgnatGrischuk** [comment]
I've added a check for the radius to ensure that the user inputs a positive number.
